version: '2'
services:
  edms-app:
    image: edms
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://edms-mysql:3306/edms?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8084:8080
  edms-mysql:
    extends:
      file: mysql.yml
      service: edms-mysql

volumes:                                             
  edms-mysql:
       driver: local
       driver_opts:
           type: none
           device: /home/srs/Documents/docker_new/volumes
           o: bind
