version: '2'
services:
  edms-mysql:
    image: mysql:8.0.2
    volumes:
      - ~/var/lib/docker/:/home/srs/Documents/docker_new/volumes
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=edms
    ports:
      - "3308:3306"
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp

volumes:                                             
  edms-mysql:
       driver: local
       driver_opts:
           type: none
           device: /home/srs/Documents/docker_new/volumes
           o: bind
